export const LangStrings = {
  en: {
    'login': "Login",
    'signUp': "Sign Up",
    'logout': 'Logout',
    'find': "Find",
    'search': 'Search',
    'dashboard': 'Dashboard',
    'browse_categories': 'Browse Categories',
    'best_3_products': 'Best 3 Products',
    'categories': 'Categories',
    'new_added_products': 'New Added Products',
    'view_all': 'View All',
    'trending_products': 'Trending Products',
    'new_rated_products': 'New Rated Products',
    'best_products_on_sale': 'Best Products On Sale',
  },
  de: {
    'login': "Login",
    'signUp': "Registrieren",
    'logout': 'Abmelden',
    'find': "Finden",
    'search': 'Schnellsuche',
    'dashboard': 'Übersicht',
    'browse_categories': 'Durchsuche Kategorien',
    'best_3_products': 'Beste 3 Produkte',
    'categories': 'Kategorien',
    'new_added_products': 'Neue hinzugefügte Produkte',
    'view_all': 'Alle ansehen',
    'trending_products': 'Trendprodukte',
    'new_rated_products': 'Neue bewertete Produkte',
    'best_products_on_sale': 'Beste Produkte im Angebot',
  },
};
